os: linux
dist: focal
language: java
jdk:
  - openjdk8
jobs:
  include: 
  - name: “test123” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom”
    script: # existing functionality
      - java -version
      - cd test
      - cat java/java_bom.json

  - name: SBOM Node
    os: linux
    language: node_js
    script:
      - cd sbom/node
      - npm install
    addons:
      sbom:
        on:
          branch: 'sbom'
        run_phase: 'after_success'
        output_format: 'cyclonedx-json'
        input_dir: '/sbom/node'
        output_dir: '/sbom/node'
      deploy:
        - provider: releases
          edge: true
          file_glob: true
          file: sbom/node/**/*
          skip_cleanup: true
          on:
            branch: sbom
        - provider: s3
          edge: true
          bucket: "sbom-test"
          skip_cleanup: true
          local_dir: sbom/node
          on:
            branch: sbom
